### ISSUE TITLE
Can't use on windows: character `*` is invalid in file names

### ISSUE THREAD

**Issue by mattn** [aperezdc/vim-template#54]
![](http://go-gyazo.appspot.com/86c5784f175ddaff.png)

**Comment by aperezdc** [comment]
This is caused by the fact that the `*` character is invalid in file Windows file systems. We have some [support to change the characters which are used as wildcards](https://github.com/aperezdc/vim-template/issues/38#issuecomment-51549928) but you will still need to rename the built-in templates yourself — probably your best solution for the moment is to download a `.zip` from GitHub and rename the files when extracting. Also, we may be moving the built-in templates to a Git submodule, so Windows users can just skip checking them out.

**Comment by muff1nman** [comment]
Would you mind trying this version of vim-template https://github.com/muff1nman/vim-template/tree/windows-path-fix?

**Comment by muff1nman** [comment]
ping @mattn

**Comment by mattn** [comment]
Sorry, I didn't use this plugin. But just to notice the issue.

**Comment by muff1nman** [comment]
Resolved via #57
