### ISSUE TITLE
where is the complete doc on how to use this plugin

### ISSUE THREAD

**Issue by branquito** [aperezdc/vim-template#78]
hi I remember there were options explained on how to set template files, where to put templates, how to specify custom dir etc.. all that is now gone from README file? why?

**Comment by aperezdc** [comment]
The documentation has been moved to [the documentation directory](/aperezdc/vim-template/blob/master/doc/template.txt). This has been done in order to allow reading the documentation from inside Vim, with the built-in help browsing mode.

You can use the link above, or from inside vim type the command `:help template` to read the documentation.

I hope this helps :-)
