### ISSUE TITLE
Unable to use custom templates

### ISSUE THREAD

**Issue by shikhanshu** [aperezdc/vim-template#81]
I am using Vundle to load the plugin. I am also setting the following two variables (tried setting both before and after loading of the plugin):
```
let g:templates_no_builtin_templates=1 <-- because I don't want it to spend time looking there
let g:templates_directory='~/.vim/code_templates' <-- this is where my templates are
```
In .vim/code_templates, I have a python template '=template=:.py' . When I create a new **test.py** file, I get these messages from debug:
```
Executing `find '~/.vim/code_templates/' -maxdepth 1 -type f -name '=template=*'`
template: ~/.vim/code_templates/=template=:.py got scored: 0
No template found
```

**Also, is there a way to make it not look in current directory and parent directories? I want the plugin to look only in "g:templates_directory" that I provide. Can such a configuration option be provided?**

**Comment by shikhanshu** [comment]
If I rename my template to =template=.py, it works fine.

The documentation should clearly say <prefix><pattern> . It currently says that plugin searches for "template:<pattern>" in the templates_directory specified which is wrong. Both template:.py and =template=:.py did not work.

Regarding being able to skip searching anywhere else but specified directory, that would be great!

**Comment by Konfekt** [comment]
Yeah, look at https://github.com/aperezdc/vim-template/issues/77

The default template naming is a bit woozy. `=template=.py` it is.

**Comment by aperezdc** [comment]
There's a bit of a history behind the names of the templates: in one form of another, I have had the Vim templates plugin in my `~/.vim/plugin` directory many, many years before cleaning it up and pushing the repo to GitHub for the first time. Since 1999, I believe.

Back then I was using [GNU Arch](https://www.gnu.org/software/gnu-arch/) for version control, which encouraged usage of certain file prefixes: `,` for temporary unimportant files, `+` for non source files which should be preserved... and `=` for “precious” files, which are not sources but Arch would put under version control anyway. And that is where the `=template=` prefix comes from: if you put a template file in a repository, you normally want to track it so everybody who gets a clone uses the same template, but it is not an actual source file by itself, and therefore the `=` prefix.

When I first uploaded the plugin to GitHub, I had still several personal repositories with templates using `=template=` as the prefix, and it did not cross my mind to change the prefix at that point. Fast forward several years, and here we are in 2015 willing to not break the setups of people who may have been using the plugin for a long time, I'd say.

**Comment by aperezdc** [comment]
BTW, I think we can close this issue.

**Comment by Konfekt** [comment]
All good, and thanks for the story behind the naming conventions. It used to be that the doc did not match the internals, which was resolved in https://github.com/aperezdc/vim-template/commit/7b3f78af03bb62c9a99943a0ad9879890b49c523

**Comment by muff1nman** [comment]
@shikhanshu - I agree in that the docs are a tad confusing. I've opened an issue to address this, but of course we'll gladly merge in any documentation PR!
